# Write your MySQL query statement below
SELECT
ROUND(COUNT(B.EVENT_DATE)/COUNT(1),2) FRACTION
FROM (SELECT PLAYER_ID, MIN(EVENT_DATE) DAY1 FROM ACTIVITY GROUP BY 1) A
LEFT JOIN ACTIVITY B
ON B.PLAYER_ID = A.PLAYER_ID
AND DATEDIFF(B.EVENT_DATE,A.DAY1)=1
AND B.GAMES_PLAYED > 0;